# Generated by Django 2.2.8 on 2020-04-15 14:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200415_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=imagekit.models.fields.ProcessedImageField(default='/static/blog/img/summary.png', upload_to='article_fengmian/%Y/%m/%d', verbose_name='图片地址'),
        ),
    ]
