# Generated by Django 2.2.8 on 2020-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200415_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=models.CharField(default='/static/blog/img/summary.png', max_length=255, verbose_name='图片地址'),
        ),
    ]
